config/routes.rb
Rails.application.routes.draw do

    devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
     	resources :products,only: [:index,:new,:create,:show,:edit,:update]
     	get 'top'=>'products#top'
    	resources :genres,only: [:index,:create,:edit,:update]
    	resources :orders,only: [:index,:show,:update] do
    	  member do
      get :current_index
      resource :order_details,only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


 devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  get 'about' => 'customer/homes#about'
  root 'customer/homes#top'

  scope module: :customer do
    resources :products,only: [:index,:show,]
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'out'
  	     patch 'withdraw'
  	  end

      resources :cart_products,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_products#destroy_all'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          get 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :addresses, dependent: :destroy
 has_many :orders
 has_many :cart_products, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana,
            :address, :phone_number,
            presence: true
  validates :post_code, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, numericality: { only_integer: true }
  validates :first_name_kana, :last_name_kana,
     format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "をカタカナで入力して下さい。"}

# 退会機能
  def active_for_authentication?
    super && (self.withdrawal_status == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:post_code,:address,:phone_number,:email,:withdrawal_status)
	end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

before_action :authenticate_customer!

  def index
  	@addresses = current_customer.addresses.page(params[:page]).per(3)
    # @addresses = Address.all
  	@address = Address.new
  end

  def create
  	@address = Address.new(address_params)
  	@address.customer_id = current_customer.id
  	@address.save
  	redirect_to customers_addresses_path
  end

  def edit
  	@address = Address.find(params[:id])
  end

  def update
  	@address = Address.find(params[:id])
  	@address.update(address_params)
  	redirect_to customers_addresses_path
  end

  def destroy
  	@address = Address.find(params[:id])
  	@address.destroy
  	redirect_to customers_addresses_path
  end

  private
  def address_params
  	params.require(:address).permit(:name, :customer_id, :address, :post_code)
  end

end

app/controllers/customer/cart_products_controller.rb
class Customer::CartProductsController < ApplicationController


 # before_action :set_cart_products, only: [:update, :destroy]
 before_action :authenticate_customer!

 def index
  @cart_products = current_customer.cart_products
  @total_price = @cart_products.sum{|cart_product|cart_product.product.price*cart_product.amount*1.1}
  @genres = Genre.all

 end

 def create
  @cart_product = CartProduct.new(cart_product_params)
  @cart_product.customer_id = current_customer.id
  # @cart_product.product_id = params[:product_id]
  # byebug
  @genres = Genre.all
  @product = Product.find(@cart_product.product_id)

  if @cart_product.save
   flash[:notice] = "#{@cart_product.product.name}をカートに追加しました。"
   redirect_to customers_cart_products_path
  else
   flash[:alert] = "個数を選択してください"
   render template: "customer/products/show"
  end
 end

 def update
  @cart_product = CartProduct.find(params[:id])
  #@cart.units += cart_params[:units].to_i
  @cart_product.update(cart_product_params)
  redirect_to customers_cart_products_path
 end

 def destroy
  @cart_product = CartProduct.find(params[:id])
  @cart_product.destroy
  flash[:alert] = "#{@cart_product.product.name}を削除しました"
  redirect_to customers_cart_products_path
 end

 def destroy_all
  @cart_product = CartProduct.all
  @cart_product.destroy_all
  flash[:alert] = "カートの商品を全て削除しました"
  redirect_to customers_cart_products_path
 end

 private

  def cart_product_params
   params.require(:cart_product).permit(:amount, :product_id)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

 before_action :authenticate_customer!, except: [:contact]

 def show
   @customer = current_customer
 end

 def edit
   @customer = current_customer
 end
 
 def update
   @customer = current_customer
    if @customer.update(customer_params)
      flash[:success] = "個人情報を編集しました"
      redirect_to customers_path
    else
      render :edit and return
    end
 end

 def out
 end


 def withdraw
    @customer = current_customer
    @customer.update(withdrawal_status: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
 end
 
 
  private
  
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :post_code, :address, :phone_number)
    end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def top
    @products = Product.joins(:genre).where(genres: { is_genres_status: true }).where(sales_status: true).order("RANDOM()").limit(4)
    #=> :asc,古い順 :desc,新しい順
    @genres = Genre.where(is_genres_status: true)
  end

  
    def about
    end
   
  private
   def product_params
     parmas.require(:product).permit(:name, :explanation, :price, :image, :sales_status, :genre_id)
   end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 # before_action :to_log, only: [:show]
 before_action :authenticate_customer!

 def confirm
  @order = Order.new
  @customer = current_customer
  @addresses = Address.where(customer_id: current_customer.id)
 end

 def create
  customer = current_customer

   #sessionを使ってデータを一時保存
  session[:order] = Order.new

  cart_products = current_customer.cart_products

  #billing_amountのための計算
  sum = 0
  cart_products.each do |cart_product|
    sum += (cart_product.product.price * 1.1).floor * cart_product.amount
  end

  session[:order][:shipping_cost] =800
  session[:order][:billing_amount]= sum + session[:order][:shipping_cost]
  session[:order][:order_status] = 0
  session[:order][:customer_id] = current_customer.id
  # ラジオボタンで選択された支払方法のenum番号を渡している
		session[:order][:payment_method] = params[:method].to_i

  #ラジオボタンの支払い方法のenum番号を渡している
  destination = params[:a_method].to_i

  #自分の住所を選択したとき
  if destination == 0
   session[:order][:post_code] = customer.post_code
   session[:order][:address] = customer.address
   session[:order][:name] = customer.last_name + customer.first_name

  elsif destination == 1
   address Address.find(params[:adress_for_order])
   session[:order][:post_code] = address.post_code
   session[:order][:address] = address.address
   session[:order][:name] = address.name

  #新しい届け先が選択されたとき
  elsif destination == 2
   session[:new_address] = 2
   session[:order][:post_code] = params[:post_code]
   session[:order][:address] = params[:address]
   session[:order][:name] = params[:name]

  end

  #届け先の漏れがあった場合リダイレクト
  if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
    redirect_to new_customers_order_path
  else
    redirect_to confirm_customers_orders_path
  end

 end

 def new
  @cart_products = current_customer.cart_products
  # byebug
 end

 def thanx
  order = Order.new(session[:order])
  order.save

  if session[:new_address]
   shipping_address = current_customer.addresses.new
   shipping_address.post_code = order.post_code
   shipping_address.address = order.address
   shipping_address.name = order.name
   shipping_address.save
   session[:new_address] = nil
  end

  #以下order_detail
  cart_products = current_customer.cart_products
  cart_products.each do |cart_product|
    order_detail = OrderDetail.new
    order_detail.order_id = order.id
    order_detail.order_quantity = cart_product.amount
    order_detail.created_status = 0
    order_detail.price = (cart_product.product.price * 1.1).floor
    order_detail.product_id = cart_product.product_id
    order_detail.save
  end

  #購入後はカート内商品削除
  cart_products.destroy_all
 end

 def index
  @orders = current_customer.orders
 end

 def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
 end





end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController

before_action :authenticate_customer!, only: [:show]

 def index
    @genres = Genre.where(is_genres_status: true)
   if params[:genre_id].nil?
      @products_all = Product.joins(:genre).where(genres: { is_genres_status: true }).where(sales_status: true).order(created_at: :desc)
      # ジャンルが有効かつ商品も販売中の商品のみ表示させる
      @products = @products_all.page(params[:page]).per(8)
      @index = "商品"
   else
      @products_all = Product.joins(:genre).where(genres: { is_genres_status: true, id: params[:genre_id] }).where(sales_status: true).order(created_at: :desc)
      @products = @products_all.page(params[:page]).per(8)
      @index = Genre.find( params[:genre_id]).name
   end
 end

 def show
   @products = Product.all
   @product = Product.find(params[:id])
   @cart_product = CartProduct.new
   @genres = Genre.all
 end

  private
  def product_params
		parmas.require(:product).permit(:name, :explanation, :price, :image, :sales_status)
	end


end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  
     before_action :reject_customer, only: [:create]
  
  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    ##downcaseは文字列に含まれている大文字を小文字に変換するメゾット
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  #9～19行まではチャンズのパクリ
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_products_helper.rb
module Customer::CartProductsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/customer/customers/edit.html.erb
<% provide(:title, "登録情報編集") %>
<% if @customer.errors.any? %>
           <% @customer.errors.full_messages.each do |message| %>
            <%= message %><br>
           <% end %>
        <% end %>
<div class="row">
  <div class="col-xs-12">

    <h2 class="head-line title_h2 text-center">登録情報編集</h2>
    
    <%= form_with model:@customer, url:customer_path, local: true ,method: :patch do |f| %>
      <%#= render "layouts/error_messages", resource: @customer %>

      <div class="col-xs-10">
        <div class="form-group col-xs-12">
          <%= f.label :"氏名", class: "col-sm-3 control-label" %>
          <%= f.text_field :last_name, class: "last_name col-sm-3 form-control-static name" %>
          <%= f.text_field :first_name, class: "first_name col-sm-3 form-control-static name" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"フリガナ", class: "col-sm-3 control-label" %>
          <%= f.text_field :last_name_kana, class: "kana_last_name col-sm-3 form-control-static name" %>
          <%= f.text_field :first_name_kana, class: "kana_first_name col-sm-3 form-control-static name" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"メールアドレス", class: "col-sm-3 control-label" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-sm-6 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"郵便番号", class: "col-sm-3 control-label" %>
          <%= f.text_field :post_code, class: "col-sm-2 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"住所", class: "col-sm-3 control-label" %>
          <%= f.text_field :address, class: "col-sm-9 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"電話番号(ハイフンなし)", class: "col-sm-3 control-label" %>
          <%= f.text_field :phone_number, class: "col-sm-2 form-control-static" %>
        </div>
      </div>

      <div class="actions col-xs-9 col-xs-offset-3">
        <%= f.submit "編集内容を保存する", class: "btn btn-primary save col-xs-6" %>
        <%= link_to '退会する', out_customers_path, class: "glyphicon glyphicon-tint btn btn-danger"%>
      </div>
    <% end %>
    <div class="col-xs-12">
      <%= link_to "戻る", customers_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
  </div>
</div>

app/views/customer/customers/out.html.erb
<% provide(:title, "退会ページ") %>
<div class="out">
  <strong>本当に退会しますか？</strong>

    <div class="out-msg">
      退会すると会員情報登録や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      <br>
      退会する場合は,「退会する」をクリックしてください。
    </div>

    <%= link_to "退会しない", customers_path, class: 'glyphicon glyphicon-home btn btn-primary' %>
    <%= link_to "退会する", withdraw_customers_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>

</div>

app/views/customer/customers/show.html.erb
<% provide(:title, "マイページ") %>
<div class="row">
	<div class="col-xs-offset-1 col-xs-8">
		<h2 class="head-line text-center title_h2">マイページ</h2>
		<p><strong class="information-link"><i class="far fa-user"></i>登録情報</strong>
		<% if notice%>
	<div class="flash notice">
	  <span id="notice"><%= notice %></span>
	</div>
<% elsif flash[:success] %>
	<div class="flash success">
  	<span id="success"><%= flash[:success] %></span>
	</div>
<% elsif flash[:alert] %>
	<div class="flash danger">
	  <span id="alert"><%= flash[:alert] %></span>
	</div>
<% end %>
			<%= link_to " 編集する", customer_edit_path, class: "glyphicon glyphicon-pencil btn btn-success" %>
			<%#= link_to " パスワードを変更する", edit_customer_registration_path, class: "glyphicon glyphicon-pencil btn btn-warning" %>
		</p>

			<table class="table table-bordered table-condensed" >
				<tbody>
					<tr>
						<td class="info col-xs-2">氏名</td>
						<td class="text-left"><%= @customer.last_name %><%= @customer.first_name %></td>
					</tr>
					<tr>
						<td class="info">カナ</td>
						<td class="text-left"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
					</tr>
					<tr>
						<td class="info">郵便番号</td>
						<td class="text-left"><%= @customer.post_code %></td>
					</tr>
					<tr>
						<td class="info">住所</td>
						<td class="text-left"><%= @customer.address %></td>
					</tr>
					<tr>
						<td class="info">電話番号</td>
						<td class="text-left"><%= @customer.phone_number %></td>
					</tr>
					<tr>
						<td class="info">メールアドレス</td>
						<td class="text-left"><%= @customer.email %></td>
					</tr>
				</tbody>
			</table>

			<div class="mypage-bottoms">
				<P><strong class="shipping-link">配送先</strong>
					<%= link_to " 一覧を見る", customers_addresses_path, data: {"turbolinks" => false}, class: "glyphicon glyphicon-folder-open btn btn-info" %>
				</p>
				<p><strong class="order-link">注文履歴</strong>
					<%= link_to " 一覧を見る", customers_orders_path, class: "glyphicon glyphicon-folder-open btn btn-info" %>
				</p>
			</div>
	</div>
</div>