config/routes.rb
Rails.application.routes.draw do

    devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
     	resources :products,only: [:index,:new,:create,:show,:edit,:update]
     	get 'top'=>'products#top'
    	resources :genres,only: [:index,:create,:edit,:update]
    	resources :orders,only: [:index,:show,:update] do
    	  member do
      get :current_index
      resource :order_details,only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


 devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  get 'about' => 'customer/homes#about'
  root 'customer/homes#top'

  scope module: :customer do
    resources :products,only: [:index,:show,]
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'out'
  	     patch 'withdraw'
  	  end

      resources :cart_products,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_products#destroy_all'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          get 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :addresses, dependent: :destroy
 has_many :orders
 has_many :cart_products, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana,
            :address, :phone_number,
            presence: true
  validates :post_code, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, numericality: { only_integer: true }
  validates :first_name_kana, :last_name_kana,
     format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "をカタカナで入力して下さい。"}

# 退会機能
  def active_for_authentication?
    super && (self.withdrawal_status == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:post_code,:address,:phone_number,:email,:withdrawal_status)
	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  # def current_index
  #   @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
  #   render :index
  # end

  # def today_order_index
  #   now = Time.current
  #   @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
  #   render :index
  # end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"

		   if @order.order_status == "入金確認"#注文ステータスが入金確認なら下の事をする
		       @order_details.update_all(created_status: 1) #製作ステータスを「製作待ちに」　更新
		   redirect_to admin_order_path(@order)
		   end
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:order_status)
	end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

before_action :authenticate_customer!

  def index
  	@addresses = current_customer.addresses.page(params[:page]).per(3)
    # @addresses = Address.all
  	@address = Address.new
  end

  def create
  	@address = Address.new(address_params)
  	@address.customer_id = current_customer.id
  	@address.save
  	redirect_to customers_addresses_path
  end

  def edit
  	@address = Address.find(params[:id])
  end

  def update
  	@address = Address.find(params[:id])
  	@address.update(address_params)
  	redirect_to customers_addresses_path
  end

  def destroy
  	@address = Address.find(params[:id])
  	@address.destroy
  	redirect_to customers_addresses_path
  end

  private
  def address_params
  	params.require(:address).permit(:name, :customer_id, :address, :post_code)
  end

end

app/controllers/customer/cart_products_controller.rb
class Customer::CartProductsController < ApplicationController


 # before_action :set_cart_products, only: [:update, :destroy]
 before_action :authenticate_customer!

 def index
  @cart_products = current_customer.cart_products
  @total_price = @cart_products.sum{|cart_product|cart_product.product.price*cart_product.amount*1.1}
  @genres = Genre.all

 end

 def create
  @cart_product = CartProduct.new(cart_product_params)
  @cart_product.customer_id = current_customer.id
  # @cart_product.product_id = params[:product_id]
  # byebug
  @genres = Genre.all
  @product = Product.find(@cart_product.product_id)

  if @cart_product.save
   flash[:notice] = "#{@cart_product.product.name}をカートに追加しました。"
   redirect_to customers_cart_products_path
  else
   flash[:alert] = "個数を選択してください"
   render template: "customer/products/show"
  end
 end

 def update
  @cart_product = CartProduct.find(params[:id])
  #@cart.units += cart_params[:units].to_i
  @cart_product.update(cart_product_params)
  redirect_to customers_cart_products_path
 end

 def destroy
  @cart_product = CartProduct.find(params[:id])
  @cart_product.destroy
  flash[:alert] = "#{@cart_product.product.name}を削除しました"
  redirect_to customers_cart_products_path
 end

 def destroy_all
  @cart_product = CartProduct.all
  @cart_product.destroy_all
  flash[:alert] = "カートの商品を全て削除しました"
  redirect_to customers_cart_products_path
 end

 private

  def cart_product_params
   params.require(:cart_product).permit(:amount, :product_id)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

 before_action :authenticate_customer!, except: [:contact]

 def show
   @customer = current_customer
 end

 def edit
   @customer = current_customer
 end
 
 def update
   @customer = current_customer
    if @customer.update(customer_params)
      flash[:success] = "個人情報を編集しました"
      redirect_to customers_path
    else
      render :edit and return
    end
 end

 def out
 end


 def withdraw
    @customer = current_customer
    @customer.update(withdrawal_status: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
 end
 
 
  private
  
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :post_code, :address, :phone_number)
    end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def top
    @products = Product.joins(:genre).where(genres: { is_genres_status: true }).where(sales_status: true).order("RANDOM()").limit(4)
    #=> :asc,古い順 :desc,新しい順
    @genres = Genre.where(is_genres_status: true)
  end

  
    def about
    end
   
  private
   def product_params
     parmas.require(:product).permit(:name, :explanation, :price, :image, :sales_status, :genre_id)
   end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 # before_action :to_log, only: [:show]
 before_action :authenticate_customer!

 def confirm
  @order = Order.new
  @customer = current_customer
  @addresses = Address.where(customer_id: current_customer.id)
 end

 def create
  customer = current_customer

   #sessionを使ってデータを一時保存
  session[:order] = Order.new

  cart_products = current_customer.cart_products

  #billing_amountのための計算
  sum = 0
  cart_products.each do |cart_product|
    sum += (cart_product.product.price * 1.1).floor * cart_product.amount
  end

  session[:order][:shipping_cost] =800
  session[:order][:billing_amount]= sum + session[:order][:shipping_cost]
  session[:order][:order_status] = 0
  session[:order][:customer_id] = current_customer.id
  # ラジオボタンで選択された支払方法のenum番号を渡している
		session[:order][:payment_method] = params[:method].to_i

  #ラジオボタンの支払い方法のenum番号を渡している
  destination = params[:a_method].to_i

  #自分の住所を選択したとき
  if destination == 0
   session[:order][:post_code] = customer.post_code
   session[:order][:address] = customer.address
   session[:order][:name] = customer.last_name + customer.first_name

  elsif destination == 1
   address Address.find(params[:adress_for_order])
   session[:order][:post_code] = address.post_code
   session[:order][:address] = address.address
   session[:order][:name] = address.name

  #新しい届け先が選択されたとき
  elsif destination == 2
   session[:new_address] = 2
   session[:order][:post_code] = params[:post_code]
   session[:order][:address] = params[:address]
   session[:order][:name] = params[:name]

  end

  #届け先の漏れがあった場合リダイレクト
  if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
    redirect_to new_customers_order_path
  else
    redirect_to confirm_customers_orders_path
  end

 end

 def new
  @cart_products = current_customer.cart_products
  # byebug
 end

 def thanx
  order = Order.new(session[:order])
  order.save

  if session[:new_address]
   shipping_address = current_customer.addresses.new
   shipping_address.post_code = order.post_code
   shipping_address.address = order.address
   shipping_address.name = order.name
   shipping_address.save
   session[:new_address] = nil
  end

  #以下order_detail
  cart_products = current_customer.cart_products
  cart_products.each do |cart_product|
    order_detail = OrderDetail.new
    order_detail.order_id = order.id
    order_detail.order_quantity = cart_product.amount
    order_detail.created_status = 0
    order_detail.price = (cart_product.product.price * 1.1).floor
    order_detail.product_id = cart_product.product_id
    order_detail.save
  end

  #購入後はカート内商品削除
  cart_products.destroy_all
 end

 def index
  @orders = current_customer.orders
 end

 def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
 end





end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController

before_action :authenticate_customer!, only: [:show]

 def index
    @genres = Genre.where(is_genres_status: true)
   if params[:genre_id].nil?
      @products_all = Product.joins(:genre).where(genres: { is_genres_status: true }).where(sales_status: true).order(created_at: :desc)
      # ジャンルが有効かつ商品も販売中の商品のみ表示させる
      @products = @products_all.page(params[:page]).per(8)
      @index = "商品"
   else
      @products_all = Product.joins(:genre).where(genres: { is_genres_status: true, id: params[:genre_id] }).where(sales_status: true).order(created_at: :desc)
      @products = @products_all.page(params[:page]).per(8)
      @index = Genre.find( params[:genre_id]).name
   end
 end

 def show
   @products = Product.all
   @product = Product.find(params[:id])
   @cart_product = CartProduct.new
   @genres = Genre.all
 end

  private
  def product_params
		parmas.require(:product).permit(:name, :explanation, :price, :image, :sales_status)
	end


end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  
     before_action :reject_customer, only: [:create]
  
  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    ##downcaseは文字列に含まれている大文字を小文字に変換するメゾット
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  #9～19行まではチャンズのパクリ
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_products_helper.rb
module Customer::CartProductsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/orders/confirm.html.erb
<body>
	<div class="panel panel-warning">
		<div class="panel-heading">
	<h2><span class="label label-default">注文情報入力</span></h2>
	</div>
	<div class="panel-body">

		<%= form_with(url: customers_orders_path, method: :post) do |form| %>
			<h3>支払方法</h3>

			<!-- form.radio_button :カラム名, :保存される値(enumの番号) -->
			<span>　　　</span><%= form.radio_button :method, 0, checked: "checked" %>
	  		<%= form.label :クレジットカード %><br>
	  		<span>　　　</span><%= form.radio_button :method, 1 %>
	  		<%= form.label :銀行振込 %>


			<h3>お届け先</h3>

			<span>　　　</span><%= form.radio_button :a_method, 0, checked: "checked" %>
			<%= form.label :ご自身の住所 %><br>
			<span>　　　　　</span><%= @customer.post_code %>
			<%= @customer.address %><br>
			<span>　　　　　</span><%= @customer.last_name %>
			<%= @customer.first_name %><br>


			<span>　　　</span><%= form.radio_button :a_method, 1 %>
			<%= form.label :登録済住所から選択 %><br>
			<!-- collection_select(プロパティ名, オブジェクトの配列, value属性の項目, テキストの項目 [, オプション])-->
			<span>　　　　　</span><%= form.collection_select :address_for_order, @addresses, :id, :address_was %><br> <!--address_for_viewからaddress_for_wasに変更しました-->


			<span>　　　</span><%= form.radio_button :a_method, 2 %>
			<%= form.label :新しいお届け先 %><br>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　郵便番号(ハイフンなし)", class: "col-xs-3 control-label"  %>
				<%= form.text_field :post_code, class: "col-xs-4 form-control-static postal_code" %>
			</div>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　住所", class: "col-xs-3 control-label" %>
				<%= form.text_field :address, class: "col-xs-7 form-control-static address" %>
			</div>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　宛名", class: "col-xs-3 control-label" %>
				<%= form.text_field :name, class: "col-xs-4 form-control-static name"%>
			</div>

	   		<%= form.submit "確認画面へ進む", class: 'btn btn-warning col-xs-6 col-xs-offset-1'%>
		<% end %>
	</div>
</body>

app/views/customer/orders/index.html.erb
<!--注文履歴一覧 -->
<div class="row">
	<div class="col-xs-12">
		<h3><strong>注文履歴一覧</strong></h3>
		<table class="table table-bordered table-condensed">
		<tr>
			<th>注文日</th>
			<th class="col-xs-3">配送先</th>
			<th class="col-xs-2">注文商品</th>
			<th class="col-xs-1">支払料金</th>
			<th class="col-xs-2">ステータス</th>
			<th class="col-xs-2">注文詳細</th>
		</tr>
		<% @orders.each do |order|%>
		<tr>
			<td class="col-xs-3"><%= order.created_at.strftime('%Y/%m/%d') %></td>
			<td class="col-xs-2"><%= order.post_code %>
				<%= order.address %>
				<%= order.name %>
			</td>
			<td class="col-xs-1">
				<% order.order_details.each do |order_detail| %>
				<%= order_detail.product.name %><br>
			<% end %>
			</td>
			<td class="col-xs-2"><%= order.billing_amount.to_s(:delimited, delimiter: ',') %></td>
			<td class="col-xs-2"><%= order.order_status %></td>
			<td><%= link_to "表示する", customers_order_path(order), class: "btn btn-primary" %></td>
		</tr>
		<% end %>
	</table>
	</div>
</div>

app/views/customer/orders/new.html.erb
<div class="row">
  <!--<div calss = "container">-->
    <h3 class = "col-12"><strong>注文情報確認</strong></h3>
    <div class="col-8">
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_products.each do |cart_product| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag( cart_product.product, :image, size: "30x20", fallback: "no_image.jpg") %>
                <%= cart_product.product.name %>
              </td>
              <td class="text-left">
                ¥<%= ((cart_product.product.price * 1.1).floor).to_s(:delimited, delimiter: ',') %>
              </td>
              <td class="text-left">
                  <%= cart_product.amount %>
              </td>
              <td class="text-left">
                ¥<%= ((cart_product.product.price * 1.1).floor * cart_product.amount).to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">配送料</th>
            <td class="text-left col-xs-5">
              <!-- sessiomのデータを表示する場合、カラム名に""つける -->
              ¥<%= session[:order]["shipping_cost"].to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-left">
              ¥<%= (session[:order]["billing_amount"] - session[:order]["shipping_cost"]).to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-left">
              ¥<%= session[:order]["billing_amount"].to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
      </table>
    </div>
    <div class="col-9 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= session[:order]["payment_method"] %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= session[:order]["post_code"] %><br>
            <%= session[:order]["address"] %><br>
            <%= session[:order]["name"]  %>
          </td>
        </tr>
      </table>

      <%= link_to "購入を確定する", thanx_customers_orders_path, class: 'btn btn-primary col-3' %>

    </div>
  <!--</div>-->
</div>

app/views/customer/orders/show.html.erb
<h3><strong>注文履歴詳細</strong></h3>

<div calss="row">
    <div class="col-xs-8">
    	<strong>注文情報</strong>
  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info">注文日</th>
          	    <td class="text-left">
                  <%= @order.created_at.strftime('%Y/%m/%d %H:%M') %>
                </td>
              </tr>
              <tr>
                <th class="info">配送先</th>
                <td class="text-left">
                  <%= @order.post_code %><br>
                  <%= @order.address %><br>
                  <%= @order.name %>
                </td>
              </tr>
              <tr>
                <th class="info">支払方法</th>
                <td class="text-left">
                  <%= @order.payment_method %>
                </td>
              </tr>
              <tr>
                <th class="info">ステータス</th>
                <td class="text-left">
                  <%= @order.order_status %>
                </td>
              </tr>
          </tbody>
        </table>
    </div>

    <div class="col-xs-3 billing">
      <strong>請求情報</strong>
        <table class="table  table-bordered table-condensed">
            <tr>
              <th class="info">配送料</th>
              <td class="col-xs-5">
                ¥<%= @order.shipping_cost.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info">商品合計</th>
              <td class="col-xs-5">
                ¥<%= (@order.billing_amount - @order.shipping_cost).to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info">ご請求金額</th>
              <td class="col-xs-5">
                ¥<%= @order.billing_amount.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
        </table>
    </div>
    <div class="col-xs-7 order-details">
    	<strong>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
          <thead>
            <tr class="info">
                <th>商品</th>
                <th>単価(税込)</th>
                <th>個数</th>
                <th>小計</th>
            </tr>
          </thead>
          <tbody>
        	<% @order_details.each do |order_detail| %>
            <tr>
                <td><%= order_detail.product.name %></td>
                <td>¥<%= (order_detail.product.price * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
                <td><%= order_detail.order_quantity %></td>
                <td>¥<%= ((order_detail.product.price * 1.1).floor * (order_detail.order_quantity)).to_s(:delimited, delimiter: ',') %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/customer/orders/thanx.html.erb
<body>
	<div class="thankspage">
		<h1 class="message">ご購入ありがとうございました！</h1>
	</div>
</body>