config/routes.rb
Rails.application.routes.draw do

    devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
     	resources :products,only: [:index,:new,:create,:show,:edit,:update]
     	get 'top'=>'products#top'
    	resources :genres,only: [:index,:create,:edit,:update]
    	resources :orders,only: [:index,:show,:update] do
    	  member do
      get :current_index
      resource :order_details,only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


 devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  get 'about' => 'customer/homes#about'
  root 'customer/homes#top'

  scope module: :customer do
    resources :products,only: [:index,:show,]
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'out'
  	     patch 'withdraw'
  	  end

      resources :cart_products,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_products#destroy_all'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          get 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

 belongs_to :customer
 has_many :order_details, dependent: :destroy
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  # def current_index
  #   @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
  #   render :index
  # end

  # def today_order_index
  #   now = Time.current
  #   @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
  #   render :index
  # end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"

		   if @order.order_status == "入金確認"#注文ステータスが入金確認なら下の事をする
		       @order_details.update_all(created_status: 1) #製作ステータスを「製作待ちに」　更新
		   redirect_to admin_order_path(@order)
		   end
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:order_status)
	end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 # before_action :to_log, only: [:show]
 before_action :authenticate_customer!

 def confirm
  @order = Order.new
  @customer = current_customer
  @addresses = Address.where(customer_id: current_customer.id)
 end

 def create
  customer = current_customer

   #sessionを使ってデータを一時保存
  session[:order] = Order.new

  cart_products = current_customer.cart_products

  #billing_amountのための計算
  sum = 0
  cart_products.each do |cart_product|
    sum += (cart_product.product.price * 1.1).floor * cart_product.amount
  end

  session[:order][:shipping_cost] =800
  session[:order][:billing_amount]= sum + session[:order][:shipping_cost]
  session[:order][:order_status] = 0
  session[:order][:customer_id] = current_customer.id
  # ラジオボタンで選択された支払方法のenum番号を渡している
		session[:order][:payment_method] = params[:method].to_i

  #ラジオボタンの支払い方法のenum番号を渡している
  destination = params[:a_method].to_i

  #自分の住所を選択したとき
  if destination == 0
   session[:order][:post_code] = customer.post_code
   session[:order][:address] = customer.address
   session[:order][:name] = customer.last_name + customer.first_name

  elsif destination == 1
   address Address.find(params[:adress_for_order])
   session[:order][:post_code] = address.post_code
   session[:order][:address] = address.address
   session[:order][:name] = address.name

  #新しい届け先が選択されたとき
  elsif destination == 2
   session[:new_address] = 2
   session[:order][:post_code] = params[:post_code]
   session[:order][:address] = params[:address]
   session[:order][:name] = params[:name]

  end

  #届け先の漏れがあった場合リダイレクト
  if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
    redirect_to new_customers_order_path
  else
    redirect_to confirm_customers_orders_path
  end

 end

 def new
  @cart_products = current_customer.cart_products
  # byebug
 end

 def thanx
  order = Order.new(session[:order])
  order.save

  if session[:new_address]
   shipping_address = current_customer.addresses.new
   shipping_address.post_code = order.post_code
   shipping_address.address = order.address
   shipping_address.name = order.name
   shipping_address.save
   session[:new_address] = nil
  end

  #以下order_detail
  cart_products = current_customer.cart_products
  cart_products.each do |cart_product|
    order_detail = OrderDetail.new
    order_detail.order_id = order.id
    order_detail.order_quantity = cart_product.amount
    order_detail.created_status = 0
    order_detail.price = (cart_product.product.price * 1.1).floor
    order_detail.product_id = cart_product.product_id
    order_detail.save
  end

  #購入後はカート内商品削除
  cart_products.destroy_all
 end

 def index
  @orders = current_customer.orders
 end

 def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
 end





end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<table class="table table-hover table-bordered table-condensed">
		  <thead>
		    <tr class="info">
		      <th class="col-xs-3"><i class="far fa-clock"></i>購入日時</th>
	      	  <th><i class="far fa-user"></i>購入者</th>
		      <th class="col-xs-1">注文個数</th>
		      <th class="col-xs-2">注文ステータス</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @orders.each do |order| %>
		      <tr>
		        <td>
		          <%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
		          	<%= order.created_at %>
		          <% end %>
		        </td>
		        <td class="text-left">
		          <%= order.name %>
		        </td>
		        <td class="text-right">
		          <%= order.order_details.sum(:order_quantity) %>
		        </td>
    	        <td>
    	      	  <%= order.order_status %>
     	        </td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
    <div class="text-center"><%= paginate(@orders) %></div>
</div>

app/views/admin/orders/show.html.erb
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
  <div class="row">
    <div class="col-xs-12" >
      <div class="col-xs-9">
		<div class="field">
		  <div class="col-xs-4">購入者</div>
		  <div class="col-xs-8"><%= @order.name %></div>
		</div>

	    <div class="field">
	      <div class="col-xs-4">配送先</div>
	      <div class="col-xs-8"><%= @order.address %></div>
	    </div>

	    <div class="field">
	      <div class="col-xs-4">支払い方法</div>
	      <div class="col-xs-8"><%= @order.payment_method %></div>
	    </div>

 	  <%= form_with model:@order, url:admin_order_path, local:true, method: :patch do |f| %>
 	    <div class="col-xs-4">注文ステータス</div>
      	<div class="col-xs-6">
        <%= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>
        </div>

      	<div class="actions">
          <div class="col-xs-2"><%= f.submit '更新'  ,class: "btn btn-primary" %></div>
      	</div>
      <% end %>
      </div>

	  <div class="buyer-order col-xs-9">
		 <table class="table table-hover table-bordered table-inverse">
			<thead>
			 <tr class="info">
			  <th class="col-xs-4">商品名</th>
			  <th>単価（税込）</th>
			  <th>数量</th>
			  <th>小計</th>
			  <th>製作ステータス</th>
       </tr>
			</thead>
				<tbody>
				<% if flash[:notice] %>
		      <div class="flash">
		       <%= flash[:notice] %>
		      </div>
	      <% end %>
				<% @order_details.each do |order_detail| %>
					<tr>
			     <td class="text-left"><%= order_detail.product.name %></td>
			     <td class="text-right">¥<%= (order_detail.price).to_s(:delimited, delimiter: ',') %></td>
			     <td class="text-right"><%= order_detail.order_quantity %></td>
			     <td class="text-right">¥<%= ((order_detail.product.price * 1.1).floor * (order_detail.order_quantity)).to_s(:delimited, delimiter: ',') %></td>
			   <%= form_with model:order_detail, url:admin_order_details_path(order_detail), local:true, method: :patch do |f| %>
			     <td>
			       <%= f.select :created_status, OrderDetail.created_statuses.keys, class: "order_status" %>
			       <%= f.submit '更新'  ,class: "btn btn-warning" %>
			     </td>
			   <% end %>
			    </tr>
				<% end %>
				</tbody>
		 </table>
	  </div>

	  <div class="col-xs-3  billing">
			<table class="table table-hover table-bordered table-condensed">
				<tr>
         <th class="info">商品合計</th>
					<td>¥<%= (@order.billing_amount-@order.shipping_cost).to_i.to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">送料</th>
					 <td>¥<%= @order.shipping_cost.to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">請求金額合計</th>
					 <td>¥<%= @order.billing_amount.to_s(:delimited) %></td>
				</tr>
		    </table>
	  </div>
    <div class="col-xs-12">
      <%= link_to "戻る", admin_orders_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
	  </div>
  </div>