config/routes.rb
Rails.application.routes.draw do

    devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
     	resources :products,only: [:index,:new,:create,:show,:edit,:update]
     	get 'top'=>'products#top'
    	resources :genres,only: [:index,:create,:edit,:update]
    	resources :orders,only: [:index,:show,:update] do
    	  member do
      get :current_index
      resource :order_details,only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


 devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  get 'about' => 'customer/homes#about'
  root 'customer/homes#top'

  scope module: :customer do
    resources :products,only: [:index,:show,]
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'out'
  	     patch 'withdraw'
  	  end

      resources :cart_products,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_products#destroy_all'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          get 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

 belongs_to :product
 belongs_to :customer

 validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :addresses, dependent: :destroy
 has_many :orders
 has_many :cart_products, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana,
            :address, :phone_number,
            presence: true
  validates :post_code, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, numericality: { only_integer: true }
  validates :first_name_kana, :last_name_kana,
     format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "をカタカナで入力して下さい。"}

# 退会機能
  def active_for_authentication?
    super && (self.withdrawal_status == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products

  validates :name, {presence: true}

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

 belongs_to :customer
 has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum created_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3, 発送:4}
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :cart_products
  has_many :orders, through: :order_details
  has_many :order_details

  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :explanation, presence: true
  validates :genre_id, presence: true
  # 値段設定時、半角数字のみ登録可能にするバリデーション
  validates :price, presence: true, format: {
    with: /\A[0-9]+\z/i,
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        flash[:notice] = "ようこそNaganoCAKEへ！！"
        root_path
    end
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/costomers/index.html.erb
<h2 class="head-line title_h2 text-center">会員一覧</h2>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <table class="table table-hover table-bordered table-condensed">
      <thead>
        <tr class="info">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td class="info col-xs-1">
              <%= customer.id %>
            </td>
            <td class="text-left">
              <%= link_to admin_customer_path(customer), class: "btn-link"  do %>
                <i class="far fa-user"></i>
                <%= full_name(customer) %>
              <% end %>
            </td>
            <td class="text-left">
              <%= customer.email %>
            </td>
            <td class="col-xs-2">
              <% if customer.is_valid == true%>
                <p><i class="fas fa-bullseye blue"></i>退会</p>
              <% else %>
                <p><i class="fas fa-bullseye red"></i>有効</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class= "text-center"><%= paginate(@customers) %></div>
</div>

app/views/admin/costomers/show.html.erb
<% provide(:title, "会員一覧") %>
  <h2 class="head-line title_h2 text-center">
    <%= full_name(@customer) %>さんの会員詳細
  </h2>
  <div class="row">
    <div class="col-xs-8">
      <div class="field">
        <p>
          顧客ID<%= @customer.id %>
          <% if @customer.is_valid == true %>
            <span>　<i class="fas fa-bullseye blue"></i>退会済
          <% elsif @customer.is_valid == false %>
            　<i class="fas fa-bullseye red"></i>有効会員</span>
          <% end %>
        </p>
      </div>
      <div class="field">
        <p>
          氏名<%= full_name(@customer) %>
        </p>
      </div>
      <div class="field">
        <p>
          フリガナ<%= full_name_kana(@customer) %>
        </p>
      </div>
      <div class="field">
        <p>
          郵便番号<%= @customer.post_code %>
        </p>
      </div>
      <div class="field">
        <p>
          住所<%= @customer.address %>
        </p>
      </div>
      <div class="field">
        <p>
          電話番号<%= @customer.phone_number %>
        </p>
      </div>
      <div class="field">
        <p>
          メールアドレス<%= @customer.email%>
        </p>
      </div>

      <div class="actions">
        <%= link_to "編集する",edit_admin_customer_path(@customer), class: "glyphicon glyphicon-pencil btn btn-success edit_shipping_addres_#{@customer.id}" %>
        <%= link_to " 注文履歴一覧を見る", current_index_admin_order_path(@customer), class: "glyphicon glyphicon-folder-open btn btn-info" %>
      </div>
    </div>
  </div>